=== KiraPFTech/fpml-toolkit-files/classification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 rel. 3 (http://www.altova.com) by Andrew Jacobs (HandCoded Consulting Ltd.) -->
<xs:schema xmlns="urn:HandCoded:Classification" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:HandCoded:Classification" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="classification" type="Classification">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="AbstractCategory">
		<xs:complexContent>
			<xs:extension base="Category"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Classification">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="abstractCategory" type="AbstractCategory"/>
			<xs:element name="refinableCategory" type="RefinableCategory"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="Category" abstract="true">
		<xs:attribute name="id" type="xs:ID"/>
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:minLength value="1"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="superClasses" type="xs:IDREFS" use="optional"/>
	</xs:complexType>
	<xs:complexType name="Exists">
		<xs:attribute name="path" type="xs:token" use="required"/>
	</xs:complexType>
	<xs:complexType name="Expr">
		<xs:sequence>
			<xs:group ref="Expr"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="If">
		<xs:sequence>
			<xs:element name="test" type="OptionalExpr"/>
			<xs:element name="then" type="OptionalExpr"/>
			<xs:element name="else" type="OptionalExpr"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OptionalExpr">
		<xs:sequence>
			<xs:group ref="Expr" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="test" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Range">
		<xs:attribute name="specification" type="xs:token" use="required"/>
		<xs:attribute name="lower" type="xs:token"/>
		<xs:attribute name="upper" type="xs:token"/>
	</xs:complexType>
	<xs:complexType name="RefinableCategory">
		<xs:complexContent>
			<xs:extension base="Category">
				<xs:sequence>
					<xs:group ref="Expr"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Release">
		<xs:attribute name="specification" type="xs:token" use="required"/>
		<xs:attribute name="version" type="xs:token" use="required"/>
	</xs:complexType>
	<xs:complexType name="XPath">
		<xs:attribute name="test" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:group name="Expr">
		<xs:choice>
			<xs:element name="xpath" type="XPath"/>
			<xs:element name="if" type="If"/>
			<xs:element name="release" type="Release"/>
			<xs:element name="range" type="Range"/>
		</xs:choice>
	</xs:group>
</xs:schema>

=== KiraPFTech/fpml-toolkit-files/isda-classification.xml
<?xml version="1.0" encoding="UTF-8"?>
<classification xmlns="urn:HandCoded:Classification" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:HandCoded:Classification classification.xsd">
	<!--
		ISDA Working Group Product Taxonomies (as at 2011-09-13)
		Copyright (C),2011 HandCoded Software Ltd.
		All rights reserved.
	-->
	<abstractCategory id="isda" name="{ISDA}"/>
	
	<!-- Credit -->
	<abstractCategory id="credit" name="{CREDIT}" superClasses="isda"/>
	
	<!-- Rates -->
	<abstractCategory id="rates" name="{RATES}" superClasses="isda"/>
	<refinableCategory id="rates-exotic" name="RATES-EXOTIC" superClasses="rates">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="product/swap | product/fra | swap | fra | capFloor | swaption"/>
			</then>
			<else>
				<xpath test="dyn:swap | dyn:fra | dyn:capFloor | dyn:bondOption | dyn:swaption "/>
			</else>
		</if>
	</refinableCategory>
	<abstractCategory id="rates-irs" name="{RATES-IR SWAP}" superClasses="rates-exotic"/>
	<refinableCategory name="RATES-IR SWAP-FIXED/FIXED" superClasses="rates-irs">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="count(//swap/swapStream) = 2 and count(//swap/swapStream/resetDates) = 0 and //swap [swapStream[1]//notionalSchedule/notionalStepSchedule/currency = swapStream[2]//notionalSchedule/notionalStepSchedule/currency]"/>
			</then>
			<else>
				<xpath test="count(dyn:swap/dyn:swapStream) = 2 and count(//dyn:swap/dyn:swapStream/dyn:resetDates) = 0 and count(dyn:swap/dyn:swapStream/dyn:calculationPeriodAmount/dyn:calculation/dyn:inflationRateCalculation) = 0 and count(dyn:swap/dyn:swapStream [dyn:calculationPeriodDates/dyn:calculationPeriodFrequency/dyn:period = 'T']) = 0 and //dyn:swap [dyn:swapStream[1]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency = dyn:swapStream[2]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency]"/>
			</else>
		</if>
	</refinableCategory>
	<refinableCategory name="RATES-IR SWAP-FIXED/FLOAT" superClasses="rates-irs">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="count(//swap/swapStream) = 2 and count(//swap/swapStream/resetDates) = 1 and
				//swap [swapStream[1]//notionalSchedule/notionalStepSchedule/currency = swapStream[2]//notionalSchedule/notionalStepSchedule/currency]"/>
			</then>
			<else>
				<xpath test="count(dyn:swap/dyn:swapStream) = 2 and count(//dyn:swap/dyn:swapStream/dyn:resetDates) = 1 and count(dyn:swap/dyn:swapStream/dyn:calculationPeriodAmount/dyn:calculation/dyn:inflationRateCalculation) = 0 and count(dyn:swap/dyn:swapStream [dyn:calculationPeriodDates/dyn:calculationPeriodFrequency/dyn:period = 'T']) = 0 and //dyn:swap [dyn:swapStream[1]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency = dyn:swapStream[2]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency]"/>
			</else>
		</if>
	</refinableCategory>
	<refinableCategory name="RATES-IR SWAP-BASIS" superClasses="rates-irs">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="count(//swap/swapStream) = 2 and count(//swap/swapStream/resetDates) = 2 and
				//swap [swapStream[1]//notionalSchedule/notionalStepSchedule/currency = swapStream[2]//notionalSchedule/notionalStepSchedule/currency]"/>
			</then>
			<else>
				<xpath test="count(dyn:swap/dyn:swapStream) = 2 and count(//dyn:swap/dyn:swapStream/dyn:resetDates) = 2 and count(dyn:swap/dyn:swapStream/dyn:calculationPeriodAmount/dyn:calculation/dyn:inflationRateCalculation) = 0 and count(dyn:swap/dyn:swapStream [dyn:calculationPeriodDates/dyn:calculationPeriodFrequency/dyn:period = 'T']) = 0 and //dyn:swap [dyn:swapStream[1]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency = dyn:swapStream[2]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency]"/>
			</else>
		</if>
	</refinableCategory>
	<refinableCategory name="RATES-IR SWAP-INFLATION" superClasses="rates-irs">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="false()"/>
			</then>
			<else>
				<xpath test="count(dyn:swap/dyn:swapStream) = 2 and dyn:swap[count(dyn:swapStream/dyn:calculationPeriodAmount/dyn:calculation/dyn:inflationRateCalculation) &gt; 0]"/>
			</else>
		</if>
	</refinableCategory>
	<refinableCategory name="RATES-IR SWAP-OIS" superClasses="rates-irs">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="false()"/>
			</then>
			<else>
				<xpath test="count(dyn:swap/dyn:swapStream) = 2 and count(dyn:swap/dyn:swapStream [dyn:calculationPeriodDates/dyn:calculationPeriodFrequency/dyn:period = 'T']) = 2"/>
			</else>
		</if>
	</refinableCategory>
	<refinableCategory name="RATES-FRA" superClasses="rates-exotic">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="product/fra | fra"/>
			</then>
			<else>
				<xpath test="dyn:fra"/>
			</else>
		</if>
	</refinableCategory>
	<refinableCategory name="RATES-CAP/FLOOR" superClasses="rates-exotic">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="capFloor/capFloorStream"/>
			</then>
			<else>
				<xpath test="dyn:capFloor/dyn:capFloorStream"/>
			</else>
		</if>
	</refinableCategory>
	<abstractCategory id="rates-xccy" name="{RATES-XCCY SWAP}" superClasses="rates-exotic"/>
	<refinableCategory name="RATES-XCCY SWAP-FIXED/FIXED" superClasses="rates-xccy">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="count(//swap/swapStream) = 2 and count(//swap/swapStream/resetDates) = 0 and
				//swap [swapStream[1]//notionalSchedule/notionalStepSchedule/currency != swapStream[2]//notionalSchedule/notionalStepSchedule/currency]"/>
			</then>
			<else>
				<xpath test="count(//dyn:swap/dyn:swapStream) = 2 and count(//dyn:swap/dyn:swapStream/dyn:resetDates) = 0 and //dyn:swap [dyn:swapStream[1]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency != dyn:swapStream[2]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency]"/>
			</else>
		</if>
	</refinableCategory>
	<refinableCategory name="RATES-XCCY SWAP-FIXED/FLOAT" superClasses="rates-xccy">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="count(//swap/swapStream) = 2 and count(//swap/swapStream/resetDates) = 1 and
				//swap [swapStream[1]//notionalSchedule/notionalStepSchedule/currency != swapStream[2]//notionalSchedule/notionalStepSchedule/currency]"/>
			</then>
			<else>
				<xpath test="count(//dyn:swap/dyn:swapStream) = 2 and count(//dyn:swap/dyn:swapStream/dyn:resetDates) = 1 and //dyn:swap [dyn:swapStream[1]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency != dyn:swapStream[2]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency]"/>
			</else>
		</if>
	</refinableCategory>
	<refinableCategory name="RATES-XCCY SWAP-BASIS" superClasses="rates-xccy">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="count(//swap/swapStream) = 2 and count(//swap/swapStream/resetDates) = 2 and
				//swap [swapStream[1]//notionalSchedule/notionalStepSchedule/currency != swapStream[2]//notionalSchedule/notionalStepSchedule/currency]"/>
			</then>
			<else>
				<xpath test="count(//dyn:swap/dyn:swapStream) = 2 and count(//dyn:swap/dyn:swapStream/dyn:resetDates) = 2 and //dyn:swap [dyn:swapStream[1]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency != dyn:swapStream[2]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency]"/>
			</else>
		</if>
	</refinableCategory>
	<abstractCategory id="rates-option" name="{RATES-OPTION}" superClasses="rates-exotic"/>
	<refinableCategory name="RATES-OPTIONS-DEBT OPTION" superClasses="rates-option">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="false ()"/>
			</then>
			<else>
				<xpath test="dyn:bondOption"/>
			</else>
		</if>
	</refinableCategory>
	<refinableCategory name="RATES-OPTIONS-SWAPTION" superClasses="rates-option">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="swaption"/>
			</then>
			<else>
				<xpath test="dyn:swaption"/>
			</else>
		</if>
	</refinableCategory>
	
	<!-- Equities -->
	<abstractCategory id="equity" name="{EQUITY}" superClasses="isda"/>
	
	<!-- FX -->
	<abstractCategory id="fx" name="{FX}" superClasses="isda"/>
	<refinableCategory name="FX-SPOT" superClasses="fx">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="fxSingleLeg and count(fxSingleLeg/exchangeRate/forwardPoints) = 0"/>
			</then>
			<else>
				<xpath test="dyn:fxSingleLeg and count(dyn:fxSingleLeg/dyn:exchangeRate/dyn:forwardPoints) = 0"/>
			</else>
		</if>
	</refinableCategory>
	
	<!-- Commodities -->
	<abstractCategory id="commodity" name="{COMMODITY}" superClasses="isda"/>

</classification>

=== KiraPFTech/fpml-toolkit-files/fpml-classification.xml
<?xml version="1.0" encoding="UTF-8"?>
<classification xmlns="urn:HandCoded:Classification" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:HandCoded:Classification classification.xsd">
	<!-- -->
	<abstractCategory id="DocumentForm" name="DocumentForm"/>
	<abstractCategory id="ShortForm" name="ShortForm" superClasses="DocumentForm"/>
	<abstractCategory id="LongForm" name="LongForm" superClasses="DocumentForm"/>
	<!-- -->
	<abstractCategory id="AssetClass" name="AssetClass"/>
	<abstractCategory id="InterestRate" name="InterestRate" superClasses="AssetClass"/>
	<abstractCategory id="Credit" name="Credit" superClasses="AssetClass"/>
	<abstractCategory id="Equity" name="Equity" superClasses="AssetClass"/>
	<abstractCategory id="ForeignExchange" name="ForeignExchange" superClasses="AssetClass"/>
	<abstractCategory id="Commodity" name="Commodity" superClasses="AssetClass"/>
	<!-- -->
	<abstractCategory id="InstrumentType" name="InstrumentType"/>
	<abstractCategory id="Securities" name="Securities" superClasses="InstrumentType"/>
	<abstractCategory id="Cash" name="Cash" superClasses="InstrumentType"/>
	<abstractCategory id="ExchangeTraded" name="ExchangeTraded" superClasses="InstrumentType"/>
	<abstractCategory id="OtcDerivative" name="OtcDerivative" superClasses="InstrumentType"/>
	<!-- -->
	<abstractCategory id="ProductType" name="ProductType"/>
	<abstractCategory id="StructuredProduct" name="StructuredProduct" superClasses="ProductType"/>
	<abstractCategory id="Payment" name="Payment" superClasses="ProductType"/>
	<abstractCategory id="Exchange" name="Exchange" superClasses="ProductType"/>
	<abstractCategory id="Derivative" name="Derivative" superClasses="ProductType"/>
	<abstractCategory id="Future" name="Future" superClasses="Derivative"/>
	<abstractCategory id="Forward" name="Forward" superClasses="Derivative"/>
	<abstractCategory id="Swap" name="Swap" superClasses="Derivative"/>
	<abstractCategory id="Option" name="Option" superClasses="Derivative"/>
	<abstractCategory id="OptionStrategy" name="OptionStrategy" superClasses="StructuredProduct"/>
	<!-- -->
	<abstractCategory id="FpML" name="FpML"/>
	<refinableCategory id="BulletPayment" name="BulletPayment" superClasses="FpML Cash Payment LongForm">
		<xpath test="bulletPayment"/>
	</refinableCategory>
	<refinableCategory id="Fx" name="Fx" superClasses="FpML ForeignExchange Exchange LongForm">
		<xpath test="fxSingleLeg"/>
	</refinableCategory>
	<refinableCategory id="FxSpot" name="FxSpot" superClasses="Fx">
		<xpath test="count(fxSingleLeg/exchangeRate/forwardPoints) = 0"/>
	</refinableCategory>
	<refinableCategory id="FxForward" name="FxForward" superClasses="Fx">
		<xpath test="fxSingleLeg/exchangeRate/forwardPoints"/>
	</refinableCategory>
	<refinableCategory name="FxSwap" superClasses="FpML ForeignExchange Swap LongForm">
		<xpath test="fxSwap"/>
	</refinableCategory>
	<abstractCategory id="FxOption" name="FxOption" superClasses="FpML ForeignExchange Option LongForm"/>
	<refinableCategory id="FxSimpleOption" name="FxSimpleOption" superClasses="FxOption">
		<xpath test="fxSimpleOption or (fxOption and count(fxOption/features) = 0)"/>
	</refinableCategory>
	<refinableCategory id="FxDigitalOption" name="FxDigitalOption" superClasses="FxOption">
		<xpath test="fxDigitalOption"/>
	</refinableCategory>
	<refinableCategory id="FxBarrierOption" name="FxBarrierOption" superClasses="FxOption">
		<xpath test="fxBarrierOption or (fxOption and fxOption/features/barrier)"/>
	</refinableCategory>
	<refinableCategory id="FxAsianOption" name="FxAsianOption" superClasses="FxOption">
		<xpath test="fxAverageRateOption or (fxOption and fxOption/features/asian)"/>
	</refinableCategory>
	<refinableCategory id="FxOptionStrategy" name="FxOptionStrategy" superClasses="FpML ForeignExchange OptionStrategy LongForm">
		<xpath test="count(strategy/fxSimpleOption) + count(strategy/fxDigitalOption) + count(strategy/fxBarrierOption) + count(strategy/fxAverageRateOption) + count(strategy/fxOption) &gt; 0"/>
	</refinableCategory>
	<refinableCategory id="InterestRateSwap" name="InterestRateSwap" superClasses="FpML InterestRate Swap LongForm">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="//swap"/>
			</then>
			<else>
				<xpath test="//dyn:swap"/>
			</else>
		</if>
	</refinableCategory>
	<refinableCategory id="CrossCurrencySwap" name="CrossCurrencySwap" superClasses="InterestRateSwap">
		<if>
			<test>
				<range specification="FpML" lower="1-0" upper="3-0"/>
			</test>
			<then>
				<xpath test="//swap/swapStream[position() &gt; 1][.//notionalSchedule/notionalStepSchedule/currency != ../swapStream[1]//notionalSchedule/notionalStepSchedule/currency]"/>
			</then>
			<else>
				<xpath test="//dyn:swap/dyn:swapStream[position() &gt; 1][.//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency != ../dyn:swapStream[1]//dyn:notionalSchedule/dyn:notionalStepSchedule/dyn:currency]"/>
			</else>
		</if>
		</refinableCategory>
	<refinableCategory id="ForwardRateAgreement" name="ForwardRateAgreement" superClasses="FpML InterestRate Exchange LongForm">
		<xpath test="fra"/>
	</refinableCategory>
	<refinableCategory id="InterestRateCap" name="InterestRateCap" superClasses="FpML InterestRate Option LongForm">
		<xpath test="capFloor/capFloorStream/calculationPeriodAmount/calculation/floatingRateCalculation/capRateSchedule"/>
	</refinableCategory>
	<refinableCategory id="InterestRateFloor" name="InterestRateFloor" superClasses="FpML InterestRate Option LongForm">
		<xpath test="capFloor/capFloorStream/calculationPeriodAmount/calculation/floatingRateCalculation/floorRateSchedule"/>
	</refinableCategory>
	<refinableCategory id="InterestRateCollar" name="InterestRateCollar" superClasses="InterestRateCap InterestRateFloor">
		<xpath test="capFloor/capFloorStream/calculationPeriodAmount/calculation/floatingRateCalculation/capRateSchedule and capFloor/capFloorStream/calculationPeriodAmount/calculation/floatingRateCalculation/floorRateSchedule"/>
	</refinableCategory>	
	<refinableCategory id="InterestRateSwaption" name="InterestRateSwaption" superClasses="FpML InterestRate Option LongForm">
		<xpath test="swaption"/>
	</refinableCategory>
	<refinableCategory id="TermDeposit" name="TermDeposit" superClasses="FpML InterestRate LongForm">
		<xpath test="termDeposit"/>
	</refinableCategory>
	<refinableCategory id="EquityOption" name="EquityOption" superClasses="FpML Equity Option LongForm">
		<xpath test="equityOption"/>
	</refinableCategory>
</classification>
